# This is a basic workflow to help you get started with Actions

name: OpenWrt docker

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
env:
 TZ: Asia/Shanghai

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag xh116/openwrt:latest
      
    - name: Docker Push
      run: docker push xh116/openwrt
